export const COUNTRY = [
  {text: 'Afghanistan', value: 'AF', key: 'AF', flag: 'AF'.toLowerCase()},
  {text: 'Åland Islands', value: 'AX', key: 'AX', flag: 'AX'.toLowerCase()},
  {text: 'Albania', value: 'AL', key: 'AL', flag: 'AL'.toLowerCase()},
  {text: 'Algeria', value: 'DZ', key: 'DZ', flag: 'DZ'.toLowerCase()},
  {text: 'American Samoa', value: 'AS', key: 'AS', flag: 'AS'.toLowerCase()},
  {text: 'AndorrA', value: 'AD', key: 'AD', flag: 'AD'.toLowerCase()},
  {text: 'Angola', value: 'AO', key: 'AO', flag: 'AO'.toLowerCase()},
  {text: 'Anguilla', value: 'AI', key: 'AI', flag: 'AI'.toLowerCase()},
  {text: 'Antigua and Barbuda', value: 'AG', key: 'AG', flag: 'AG'.toLowerCase()},
  {text: 'Argentina', value: 'AR', key: 'AR', flag: 'AR'.toLowerCase()},
  {text: 'Armenia', value: 'AM', key: 'AM', flag: 'AM'.toLowerCase()},
  {text: 'Aruba', value: 'AW', key: 'AW', flag: 'AW'.toLowerCase()},
  {text: 'Australia', value: 'AU', key: 'AU', flag: 'AU'.toLowerCase()},
  {text: 'Austria', value: 'AT', key: 'AT', flag: 'AT'.toLowerCase()},
  {text: 'Azerbaijan', value: 'AZ', key: 'AZ', flag: 'AZ'.toLowerCase()},
  {text: 'Bahamas', value: 'BS', key: 'BS', flag: 'BS'.toLowerCase()},
  {text: 'Bahrain', value: 'BH', key: 'BH', flag: 'BH'.toLowerCase()},
  {text: 'Bangladesh', value: 'BD', key: 'BD', flag: 'BD'.toLowerCase()},
  {text: 'Barbados', value: 'BB', key: 'BB', flag: 'BB'.toLowerCase()},
  {text: 'Belarus', value: 'BY', key: 'BY', flag: 'BY'.toLowerCase()},
  {text: 'Belgium', value: 'BE', key: 'BE', flag: 'BE'.toLowerCase()},
  {text: 'Belize', value: 'BZ', key: 'BZ', flag: 'BZ'.toLowerCase()},
  {text: 'Benin', value: 'BJ', key: 'BJ', flag: 'BJ'.toLowerCase()},
  {text: 'Bermuda', value: 'BM', key: 'BM', flag: 'BM'.toLowerCase()},
  {text: 'Bhutan', value: 'BT', key: 'BT', flag: 'BT'.toLowerCase()},
  {text: 'Bolivia', value: 'BO', key: 'BO', flag: 'BO'.toLowerCase()},
  {text: 'Bosnia and Herzegovina', value: 'BA', key: 'BA', flag: 'BA'.toLowerCase()},
  {text: 'Botswana', value: 'BW', key: 'BW', flag: 'BW'.toLowerCase()},
  {text: 'Bouvet Island', value: 'BV', key: 'BV', flag: 'BV'.toLowerCase()},
  {text: 'Brazil', value: 'BR', key: 'BR', flag: 'BR'.toLowerCase()},
  {text: 'British Indian Ocean Territory', value: 'IO', key: 'IO', flag: 'IO'.toLowerCase()},
  {text: 'Brunei Darussalam', value: 'BN', key: 'BN', flag: 'BN'.toLowerCase()},
  {text: 'Bulgaria', value: 'BG', key: 'BG', flag: 'BG'.toLowerCase()},
  {text: 'Burkina Faso', value: 'BF', key: 'BF', flag: 'BF'.toLowerCase()},
  {text: 'Burundi', value: 'BI', key: 'BI', flag: 'BI'.toLowerCase()},
  {text: 'Cambodia', value: 'KH', key: 'KH', flag: 'KH'.toLowerCase()},
  {text: 'Cameroon', value: 'CM', key: 'CM', flag: 'CM'.toLowerCase()},
  {text: 'Canada', value: 'CA', key: 'CA', flag: 'CA'.toLowerCase()},
  {text: 'Cape Verde', value: 'CV', key: 'CV', flag: 'CV'.toLowerCase()},
  {text: 'Cayman Islands', value: 'KY', key: 'KY', flag: 'KY'.toLowerCase()},
  {text: 'Central African Republic', value: 'CF', key: 'CF', flag: 'CF'.toLowerCase()},
  {text: 'Chad', value: 'TD', key: 'TD', flag: 'TD'.toLowerCase()},
  {text: 'Chile', value: 'CL', key: 'CL', flag: 'CL'.toLowerCase()},
  {text: 'China', value: 'CN', key: 'CN', flag: 'CN'.toLowerCase()},
  {text: 'Christmas Island', value: 'CX', key: 'CX', flag: 'CX'.toLowerCase()},
  {text: 'Cocos (Keeling) Islands', value: 'CC', key: 'CC', flag: 'CC'.toLowerCase()},
  {text: 'Colombia', value: 'CO', key: 'CO', flag: 'CO'.toLowerCase()},
  {text: 'Comoros', value: 'KM', key: 'KM', flag: 'KM'.toLowerCase()},
  {text: 'Congo', value: 'CG', key: 'CG', flag: 'CG'.toLowerCase()},
  {text: 'Congo, The Democratic Republic of the', value: 'CD', key: 'CD', flag: 'CD'.toLowerCase()},
  {text: 'Cook Islands', value: 'CK', key: 'CK', flag: 'CK'.toLowerCase()},
  {text: 'Costa Rica', value: 'CR', key: 'CR', flag: 'CR'.toLowerCase()},
  {text: 'Cote D\'Ivoire', value: 'CI', key: 'CI', flag: 'CI'.toLowerCase()},
  {text: 'Croatia', value: 'HR', key: 'HR', flag: 'HR'.toLowerCase()},
  {text: 'Cuba', value: 'CU', key: 'CU', flag: 'CU'.toLowerCase()},
  {text: 'Cyprus', value: 'CY', key: 'CY', flag: 'CY'.toLowerCase()},
  {text: 'Czech Republic', value: 'CZ', key: 'CZ', flag: 'CZ'.toLowerCase()},
  {text: 'Denmark', value: 'DK', key: 'DK', flag: 'DK'.toLowerCase()},
  {text: 'Djibouti', value: 'DJ', key: 'DJ', flag: 'DJ'.toLowerCase()},
  {text: 'Dominica', value: 'DM', key: 'DM', flag: 'DM'.toLowerCase()},
  {text: 'Dominican Republic', value: 'DO', key: 'DO', flag: 'DO'.toLowerCase()},
  {text: 'Ecuador', value: 'EC', key: 'EC', flag: 'EC'.toLowerCase()},
  {text: 'Egypt', value: 'EG', key: 'EG', flag: 'EG'.toLowerCase()},
  {text: 'El Salvador', value: 'SV', key: 'SV', flag: 'SV'.toLowerCase()},
  {text: 'Equatorial Guinea', value: 'GQ', key: 'GQ', flag: 'GQ'.toLowerCase()},
  {text: 'Eritrea', value: 'ER', key: 'ER', flag: 'ER'.toLowerCase()},
  {text: 'Estonia', value: 'EE', key: 'EE', flag: 'EE'.toLowerCase()},
  {text: 'Ethiopia', value: 'ET', key: 'ET', flag: 'ET'.toLowerCase()},
  {text: 'Falkland Islands (Malvinas)', value: 'FK', key: 'FK', flag: 'FK'.toLowerCase()},
  {text: 'Faroe Islands', value: 'FO', key: 'FO', flag: 'FO'.toLowerCase()},
  {text: 'Fiji', value: 'FJ', key: 'FJ', flag: 'FJ'.toLowerCase()},
  {text: 'Finland', value: 'FI', key: 'FI', flag: 'FI'.toLowerCase()},
  {text: 'France', value: 'FR', key: 'FR', flag: 'FR'.toLowerCase()},
  {text: 'French Guiana', value: 'GF', key: 'GF', flag: 'GF'.toLowerCase()},
  {text: 'French Polynesia', value: 'PF', key: 'PF', flag: 'PF'.toLowerCase()},
  {text: 'French Southern Territories', value: 'TF', key: 'TF', flag: 'TF'.toLowerCase()},
  {text: 'Gabon', value: 'GA', key: 'GA', flag: 'GA'.toLowerCase()},
  {text: 'Gambia', value: 'GM', key: 'GM', flag: 'GM'.toLowerCase()},
  {text: 'Georgia', value: 'GE', key: 'GE', flag: 'GE'.toLowerCase()},
  {text: 'Germany', value: 'DE', key: 'DE', flag: 'DE'.toLowerCase()},
  {text: 'Ghana', value: 'GH', key: 'GH', flag: 'GH'.toLowerCase()},
  {text: 'Gibraltar', value: 'GI', key: 'GI', flag: 'GI'.toLowerCase()},
  {text: 'Greece', value: 'GR', key: 'GR', flag: 'GR'.toLowerCase()},
  {text: 'Greenland', value: 'GL', key: 'GL', flag: 'GL'.toLowerCase()},
  {text: 'Grenada', value: 'GD', key: 'GD', flag: 'GD'.toLowerCase()},
  {text: 'Guadeloupe', value: 'GP', key: 'GP', flag: 'GP'.toLowerCase()},
  {text: 'Guam', value: 'GU', key: 'GU', flag: 'GU'.toLowerCase()},
  {text: 'Guatemala', value: 'GT', key: 'GT', flag: 'GT'.toLowerCase()},
  {text: 'Guinea', value: 'GN', key: 'GN', flag: 'GN'.toLowerCase()},
  {text: 'Guinea-Bissau', value: 'GW', key: 'GW', flag: 'GW'.toLowerCase()},
  {text: 'Guyana', value: 'GY', key: 'GY', flag: 'GY'.toLowerCase()},
  {text: 'Haiti', value: 'HT', key: 'HT', flag: 'HT'.toLowerCase()},
  {text: 'Heard Island and Mcdonald Islands', value: 'HM', key: 'HM', flag: 'HM'.toLowerCase()},
  {text: 'Holy See (Vatican City State)', value: 'VA', key: 'VA', flag: 'VA'.toLowerCase()},
  {text: 'Honduras', value: 'HN', key: 'HN', flag: 'HN'.toLowerCase()},
  {text: 'Hong Kong', value: 'HK', key: 'HK', flag: 'HK'.toLowerCase()},
  {text: 'Hungary', value: 'HU', key: 'HU', flag: 'HU'.toLowerCase()},
  {text: 'Iceland', value: 'IS', key: 'IS', flag: 'IS'.toLowerCase()},
  {text: 'India', value: 'IN', key: 'IN', flag: 'IN'.toLowerCase()},
  {text: 'Indonesia', value: 'ID', key: 'ID', flag: 'ID'.toLowerCase()},
  {text: 'Iran, Islamic Republic Of', value: 'IR', key: 'IR', flag: 'IR'.toLowerCase()},
  {text: 'Iraq', value: 'IQ', key: 'IQ', flag: 'IQ'.toLowerCase()},
  {text: 'Ireland', value: 'IE', key: 'IE', flag: 'IE'.toLowerCase()},
  {text: 'Israel', value: 'IL', key: 'IL', flag: 'IL'.toLowerCase()},
  {text: 'Italy', value: 'IT', key: 'IT', flag: 'IT'.toLowerCase()},
  {text: 'Jamaica', value: 'JM', key: 'JM', flag: 'JM'.toLowerCase()},
  {text: 'Japan', value: 'JP', key: 'JP', flag: 'JP'.toLowerCase()},
  {text: 'Jordan', value: 'JO', key: 'JO', flag: 'JO'.toLowerCase()},
  {text: 'Kazakhstan', value: 'KZ', key: 'KZ', flag: 'KZ'.toLowerCase()},
  {text: 'Kenya', value: 'KE', key: 'KE', flag: 'KE'.toLowerCase()},
  {text: 'Kiribati', value: 'KI', key: 'KI', flag: 'KI'.toLowerCase()},
  {text: 'Korea, Democratic People\'S Republic of', value: 'KP', key: 'KP', flag: 'KP'.toLowerCase()},
  {text: 'Korea, Republic of', value: 'KR', key: 'KR', flag: 'KR'.toLowerCase()},
  {text: 'Kuwait', value: 'KW', key: 'KW', flag: 'KW'.toLowerCase()},
  {text: 'Kyrgyzstan', value: 'KG', key: 'KG', flag: 'KG'.toLowerCase()},
  {text: 'Lao People\'S Democratic Republic', value: 'LA', key: 'LA', flag: 'LA'.toLowerCase()},
  {text: 'Latvia', value: 'LV', key: 'LV', flag: 'LV'.toLowerCase()},
  {text: 'Lebanon', value: 'LB', key: 'LB', flag: 'LB'.toLowerCase()},
  {text: 'Lesotho', value: 'LS', key: 'LS', flag: 'LS'.toLowerCase()},
  {text: 'Liberia', value: 'LR', key: 'LR', flag: 'LR'.toLowerCase()},
  {text: 'Libyan Arab Jamahiriya', value: 'LY', key: 'LY', flag: 'LY'.toLowerCase()},
  {text: 'Liechtenstein', value: 'LI', key: 'LI', flag: 'LI'.toLowerCase()},
  {text: 'Lithuania', value: 'LT', key: 'LT', flag: 'LT'.toLowerCase()},
  {text: 'Luxembourg', value: 'LU', key: 'LU', flag: 'LU'.toLowerCase()},
  {text: 'Macao', value: 'MO', key: 'MO', flag: 'MO'.toLowerCase()},
  {text: 'Macedonia, The Former Yugoslav Republic of', value: 'MK', key: 'MK', flag: 'MK'.toLowerCase()},
  {text: 'Madagascar', value: 'MG', key: 'MG', flag: 'MG'.toLowerCase()},
  {text: 'Malawi', value: 'MW', key: 'MW', flag: 'MW'.toLowerCase()},
  {text: 'Malaysia', value: 'MY', key: 'MY', flag: 'MY'.toLowerCase()},
  {text: 'Maldives', value: 'MV', key: 'MV', flag: 'MV'.toLowerCase()},
  {text: 'Mali', value: 'ML', key: 'ML', flag: 'ML'.toLowerCase()},
  {text: 'Malta', value: 'MT', key: 'MT', flag: 'MT'.toLowerCase()},
  {text: 'Marshall Islands', value: 'MH', key: 'MH', flag: 'MH'.toLowerCase()},
  {text: 'Martinique', value: 'MQ', key: 'MQ', flag: 'MQ'.toLowerCase()},
  {text: 'Mauritania', value: 'MR', key: 'MR', flag: 'MR'.toLowerCase()},
  {text: 'Mauritius', value: 'MU', key: 'MU', flag: 'MU'.toLowerCase()},
  {text: 'Mayotte', value: 'YT', key: 'YT', flag: 'YT'.toLowerCase()},
  {text: 'Mexico', value: 'MX', key: 'MX', flag: 'MX'.toLowerCase()},
  {text: 'Micronesia, Federated States of', value: 'FM', key: 'FM', flag: 'FM'.toLowerCase()},
  {text: 'Moldova, Republic of', value: 'MD', key: 'MD', flag: 'MD'.toLowerCase()},
  {text: 'Monaco', value: 'MC', key: 'MC', flag: 'MC'.toLowerCase()},
  {text: 'Mongolia', value: 'MN', key: 'MN', flag: 'MN'.toLowerCase()},
  {text: 'Montserrat', value: 'MS', key: 'MS', flag: 'MS'.toLowerCase()},
  {text: 'Morocco', value: 'MA', key: 'MA', flag: 'MA'.toLowerCase()},
  {text: 'Mozambique', value: 'MZ', key: 'MZ', flag: 'MZ'.toLowerCase()},
  {text: 'Myanmar', value: 'MM', key: 'MM', flag: 'MM'.toLowerCase()},
  {text: 'Namibia', value: 'NA', key: 'NA', flag: 'NA'.toLowerCase()},
  {text: 'Nauru', value: 'NR', key: 'NR', flag: 'NR'.toLowerCase()},
  {text: 'Nepal', value: 'NP', key: 'NP', flag: 'NP'.toLowerCase()},
  {text: 'Netherlands', value: 'NL', key: 'NL', flag: 'NL'.toLowerCase()},
  {text: 'Netherlands Antilles', value: 'AN', key: 'AN', flag: 'AN'.toLowerCase()},
  {text: 'New Caledonia', value: 'NC', key: 'NC', flag: 'NC'.toLowerCase()},
  {text: 'New Zealand', value: 'NZ', key: 'NZ', flag: 'NZ'.toLowerCase()},
  {text: 'Nicaragua', value: 'NI', key: 'NI', flag: 'NI'.toLowerCase()},
  {text: 'Niger', value: 'NE', key: 'NE', flag: 'NE'.toLowerCase()},
  {text: 'Nigeria', value: 'NG', key: 'NG', flag: 'NG'.toLowerCase()},
  {text: 'Niue', value: 'NU', key: 'NU', flag: 'NU'.toLowerCase()},
  {text: 'Norfolk Island', value: 'NF', key: 'NF', flag: 'NF'.toLowerCase()},
  {text: 'Northern Mariana Islands', value: 'MP', key: 'MP', flag: 'MP'.toLowerCase()},
  {text: 'Norway', value: 'NO', key: 'NO', flag: 'NO'.toLowerCase()},
  {text: 'Oman', value: 'OM', key: 'OM', flag: 'OM'.toLowerCase()},
  {text: 'Pakistan', value: 'PK', key: 'PK', flag: 'PK'.toLowerCase()},
  {text: 'Palau', value: 'PW', key: 'PW', flag: 'PW'.toLowerCase()},
  {text: 'Palestinian Territory, Occupied', value: 'PS', key: 'PS', flag: 'PS'.toLowerCase()},
  {text: 'Panama', value: 'PA', key: 'PA', flag: 'PA'.toLowerCase()},
  {text: 'Papua New Guinea', value: 'PG', key: 'PG', flag: 'PG'.toLowerCase()},
  {text: 'Paraguay', value: 'PY', key: 'PY', flag: 'PY'.toLowerCase()},
  {text: 'Peru', value: 'PE', key: 'PE', flag: 'PE'.toLowerCase()},
  {text: 'Philippines', value: 'PH', key: 'PH', flag: 'PH'.toLowerCase()},
  {text: 'Pitcairn', value: 'PN', key: 'PN', flag: 'PN'.toLowerCase()},
  {text: 'Poland', value: 'PL', key: 'PL', flag: 'PL'.toLowerCase()},
  {text: 'Portugal', value: 'PT', key: 'PT', flag: 'PT'.toLowerCase()},
  {text: 'Puerto Rico', value: 'PR', key: 'PR', flag: 'PR'.toLowerCase()},
  {text: 'Qatar', value: 'QA', key: 'QA', flag: 'QA'.toLowerCase()},
  {text: 'Reunion', value: 'RE', key: 'RE', flag: 'RE'.toLowerCase()},
  {text: 'Romania', value: 'RO', key: 'RO', flag: 'RO'.toLowerCase()},
  {text: 'Russian Federation', value: 'RU', key: 'RU', flag: 'RU'.toLowerCase()},
  {text: 'RWANDA', value: 'RW', key: 'RW', flag: 'RW'.toLowerCase()},
  {text: 'Saint Helena', value: 'SH', key: 'SH', flag: 'SH'.toLowerCase()},
  {text: 'Saint Kitts and Nevis', value: 'KN', key: 'KN', flag: 'KN'.toLowerCase()},
  {text: 'Saint Lucia', value: 'LC', key: 'LC', flag: 'LC'.toLowerCase()},
  {text: 'Saint Pierre and Miquelon', value: 'PM', key: 'PM', flag: 'PM'.toLowerCase()},
  {text: 'Saint Vincent and the Grenadines', value: 'VC', key: 'VC', flag: 'VC'.toLowerCase()},
  {text: 'Samoa', value: 'WS', key: 'WS', flag: 'WS'.toLowerCase()},
  {text: 'San Marino', value: 'SM', key: 'SM', flag: 'SM'.toLowerCase()},
  {text: 'Sao Tome and Principe', value: 'ST', key: 'ST', flag: 'ST'.toLowerCase()},
  {text: 'Saudi Arabia', value: 'SA', key: 'SA', flag: 'SA'.toLowerCase()},
  {text: 'Senegal', value: 'SN', key: 'SN', flag: 'SN'.toLowerCase()},
  {text: 'Serbia and Montenegro', value: 'CS', key: 'CS', flag: 'CS'.toLowerCase()},
  {text: 'Seychelles', value: 'SC', key: 'SC', flag: 'SC'.toLowerCase()},
  {text: 'Sierra Leone', value: 'SL', key: 'SL', flag: 'SL'.toLowerCase()},
  {text: 'Singapore', value: 'SG', key: 'SG', flag: 'SG'.toLowerCase()},
  {text: 'Slovakia', value: 'SK', key: 'SK', flag: 'SK'.toLowerCase()},
  {text: 'Slovenia', value: 'SI', key: 'SI', flag: 'SI'.toLowerCase()},
  {text: 'Solomon Islands', value: 'SB', key: 'SB', flag: 'SB'.toLowerCase()},
  {text: 'Somalia', value: 'SO', key: 'SO', flag: 'SO'.toLowerCase()},
  {text: 'South Africa', value: 'ZA', key: 'ZA', flag: 'ZA'.toLowerCase()},
  {text: 'South Georgia and the South Sandwich Islands', value: 'GS', key: 'GS', flag: 'GS'.toLowerCase()},
  {text: 'Spain', value: 'ES', key: 'ES', flag: 'ES'.toLowerCase()},
  {text: 'Sri Lanka', value: 'LK', key: 'LK', flag: 'LK'.toLowerCase()},
  {text: 'Sudan', value: 'SD', key: 'SD', flag: 'SD'.toLowerCase()},
  {text: 'Suritext', value: 'SR', key: 'SR', flag: 'SR'.toLowerCase()},
  {text: 'Svalbard and Jan Mayen', value: 'SJ', key: 'SJ', flag: 'SJ'.toLowerCase()},
  {text: 'Swaziland', value: 'SZ', key: 'SZ', flag: 'SZ'.toLowerCase()},
  {text: 'Sweden', value: 'SE', key: 'SE', flag: 'SE'.toLowerCase()},
  {text: 'Switzerland', value: 'CH', key: 'CH', flag: 'CH'.toLowerCase()},
  {text: 'Syrian Arab Republic', value: 'SY', key: 'SY', flag: 'SY'.toLowerCase()},
  {text: 'Taiwan, Province of China', value: 'TW', key: 'TW', flag: 'TW'.toLowerCase()},
  {text: 'Tajikistan', value: 'TJ', key: 'TJ', flag: 'TJ'.toLowerCase()},
  {text: 'Tanzania, United Republic of', value: 'TZ', key: 'TZ', flag: 'TZ'.toLowerCase()},
  {text: 'Thailand', value: 'TH', key: 'TH', flag: 'TH'.toLowerCase()},
  {text: 'Timor-Leste', value: 'TL', key: 'TL', flag: 'TL'.toLowerCase()},
  {text: 'Togo', value: 'TG', key: 'TG', flag: 'TG'.toLowerCase()},
  {text: 'Tokelau', value: 'TK', key: 'TK', flag: 'TK'.toLowerCase()},
  {text: 'Tonga', value: 'TO', key: 'TO', flag: 'TO'.toLowerCase()},
  {text: 'Trinidad and Tobago', value: 'TT', key: 'TT', flag: 'TT'.toLowerCase()},
  {text: 'Tunisia', value: 'TN', key: 'TN', flag: 'TN'.toLowerCase()},
  {text: 'Turkey', value: 'TR', key: 'TR', flag: 'TR'.toLowerCase()},
  {text: 'Turkmenistan', value: 'TM', key: 'TM', flag: 'TM'.toLowerCase()},
  {text: 'Turks and Caicos Islands', value: 'TC', key: 'TC', flag: 'TC'.toLowerCase()},
  {text: 'Tuvalu', value: 'TV', key: 'TV', flag: 'TV'.toLowerCase()},
  {text: 'Uganda', value: 'UG', key: 'UG', flag: 'UG'.toLowerCase()},
  {text: 'Ukraine', value: 'UA', key: 'UA', flag: 'UA'.toLowerCase()},
  {text: 'United Arab Emirates', value: 'AE', key: 'AE', flag: 'AE'.toLowerCase()},
  {text: 'United Kingdom', value: 'GB', key: 'GB', flag: 'GB'.toLowerCase()},
  {text: 'United States', value: 'US', key: 'US', flag: 'US'.toLowerCase()},
  {text: 'United States Minor Outlying Islands', value: 'UM', key: 'UM', flag: 'UM'.toLowerCase()},
  {text: 'Uruguay', value: 'UY', key: 'UY', flag: 'UY'.toLowerCase()},
  {text: 'Uzbekistan', value: 'UZ', key: 'UZ', flag: 'UZ'.toLowerCase()},
  {text: 'Vanuatu', value: 'VU', key: 'VU', flag: 'VU'.toLowerCase()},
  {text: 'Venezuela', value: 'VE', key: 'VE', flag: 'VE'.toLowerCase()},
  {text: 'Viet Nam', value: 'VN', key: 'VN', flag: 'VN'.toLowerCase()},
  {text: 'Virgin Islands, British', value: 'VG', key: 'VG', flag: 'VG'.toLowerCase()},
  {text: 'Virgin Islands, U.S.', value: 'VI', key: 'VI', flag: 'VI'.toLowerCase()},
  {text: 'Wallis and Futuna', value: 'WF', key: 'WF', flag: 'WF'.toLowerCase()},
  {text: 'Western Sahara', value: 'EH', key: 'EH', flag: 'EH'.toLowerCase()},
  {text: 'Yemen', value: 'YE', key: 'YE', flag: 'YE'.toLowerCase()},
  {text: 'Zambia', value: 'ZM', key: 'ZM', flag: 'ZM'.toLowerCase()},
  {text: 'Zimbabwe', value: 'ZW', key: 'ZW', flag: 'ZW'.toLowerCase()}
];
export const LANG = {
    'KOREAN' : 'ko'
    , "ENGLISH" : 'en'
    , "FRENCH" : 'fr'
    , "CHINESE" : 'zh-han'
    , "JAPANESE" : 'ja'
};