export const COUNTRY = [
  {text: 'Afghanistan', value: 'AF', key: 'AF', flag: 'AF'.toLowerCase()},
  {text: 'Albania', value: 'AL', key: 'AL', flag: 'AL'.toLowerCase()},
  {text: 'Algeria', value: 'DZ', key: 'DZ', flag: 'DZ'.toLowerCase()},
  {text: 'American Samoa', value: 'AS', key: 'AS', flag: 'AS'.toLowerCase()},
  {text: 'AndorrA', value: 'AD', key: 'AD', flag: 'AD'.toLowerCase()},
  {text: 'Angola', value: 'AO', key: 'AO', flag: 'AO'.toLowerCase()},
  {text: 'Anguilla', value: 'AI', key: 'AI', flag: 'AI'.toLowerCase()},
  {text: 'Antigua and Barbuda', value: 'AG', key: 'AG', flag: 'AG'.toLowerCase()},
  {text: 'Argentina', value: 'AR', key: 'AR', flag: 'AR'.toLowerCase()},
  {text: 'Armenia', value: 'AM', key: 'AM', flag: 'AM'.toLowerCase()},
  {text: 'Aruba', value: 'AW', key: 'AW', flag: 'AW'.toLowerCase()},
  {text: 'Australia', value: 'AU', key: 'AU', flag: 'AU'.toLowerCase()},
  {text: 'Austria', value: 'AT', key: 'AT', flag: 'AT'.toLowerCase()},
  {text: 'Azerbaijan', value: 'AZ', key: 'AZ', flag: 'AZ'.toLowerCase()},
  {text: 'Bahamas', value: 'BS', key: 'BS', flag: 'BS'.toLowerCase()},
  {text: 'Bahrain', value: 'BH', key: 'BH', flag: 'BH'.toLowerCase()},
  {text: 'Bangladesh', value: 'BD', key: 'BD', flag: 'BD'.toLowerCase()},
  {text: 'Barbados', value: 'BB', key: 'BB', flag: 'BB'.toLowerCase()},
  {text: 'Belarus', value: 'BY', key: 'BY', flag: 'BY'.toLowerCase()},
  {text: 'Belgium', value: 'BE', key: 'BE', flag: 'BE'.toLowerCase()},
  {text: 'Belize', value: 'BZ', key: 'BZ', flag: 'BZ'.toLowerCase()},
  {text: 'Benin', value: 'BJ', key: 'BJ', flag: 'BJ'.toLowerCase()},
  {text: 'Bermuda', value: 'BM', key: 'BM', flag: 'BM'.toLowerCase()},
  {text: 'Bhutan', value: 'BT', key: 'BT', flag: 'BT'.toLowerCase()},
  {text: 'Bolivia', value: 'BO', key: 'BO', flag: 'BO'.toLowerCase()},
  {text: 'Bosnia and Herzegovina', value: 'BA', key: 'BA', flag: 'BA'.toLowerCase()},
  {text: 'Botswana', value: 'BW', key: 'BW', flag: 'BW'.toLowerCase()},
  {text: 'Bouvet Island', value: 'BV', key: 'BV', flag: 'BV'.toLowerCase()},
  {text: 'Brazil', value: 'BR', key: 'BR', flag: 'BR'.toLowerCase()},
  {text: 'British Indian Ocean Territory', value: 'IO', key: 'IO', flag: 'IO'.toLowerCase()},
  {text: 'Brunei Darussalam', value: 'BN', key: 'BN', flag: 'BN'.toLowerCase()},
  {text: 'Bulgaria', value: 'BG', key: 'BG', flag: 'BG'.toLowerCase()},
  {text: 'Burkina Faso', value: 'BF', key: 'BF', flag: 'BF'.toLowerCase()},
  {text: 'Burundi', value: 'BI', key: 'BI', flag: 'BI'.toLowerCase()},
  {text: 'Cambodia', value: 'KH', key: 'KH', flag: 'KH'.toLowerCase()},
  {text: 'Cameroon', value: 'CM', key: 'CM', flag: 'CM'.toLowerCase()},
  {text: 'Canada', value: 'CA', key: 'CA', flag: 'CA'.toLowerCase()},
  {text: 'Cape Verde', value: 'CV', key: 'CV', flag: 'CV'.toLowerCase()},
  {text: 'Cayman Islands', value: 'KY', key: 'KY', flag: 'KY'.toLowerCase()},
  {text: 'Central African Republic', value: 'CF', key: 'CF', flag: 'CF'.toLowerCase()},
  {text: 'Chad', value: 'TD', key: 'TD', flag: 'TD'.toLowerCase()},
  {text: 'Chile', value: 'CL', key: 'CL', flag: 'CL'.toLowerCase()},
  {text: 'China', value: 'CN', key: 'CN', flag: 'CN'.toLowerCase()},
  {text: 'Christmas Island', value: 'CX', key: 'CX', flag: 'CX'.toLowerCase()},
  {text: 'Cocos (Keeling) Islands', value: 'CC', key: 'CC', flag: 'CC'.toLowerCase()},
  {text: 'Colombia', value: 'CO', key: 'CO', flag: 'CO'.toLowerCase()},
  {text: 'Comoros', value: 'KM', key: 'KM', flag: 'KM'.toLowerCase()},
  {text: 'Congo', value: 'CG', key: 'CG', flag: 'CG'.toLowerCase()},
  {text: 'Congo, The Democratic Republic of the', value: 'CD', key: 'CD', flag: 'CD'.toLowerCase()},
  {text: 'Cook Islands', value: 'CK', key: 'CK', flag: 'CK'.toLowerCase()},
  {text: 'Costa Rica', value: 'CR', key: 'CR', flag: 'CR'.toLowerCase()},
  {text: 'Cote D\'Ivoire', value: 'CI', key: 'CI', flag: 'CI'.toLowerCase()},
  {text: 'Croatia', value: 'HR', key: 'HR', flag: 'HR'.toLowerCase()},
  {text: 'Cuba', value: 'CU', key: 'CU', flag: 'CU'.toLowerCase()},
  {text: 'Cyprus', value: 'CY', key: 'CY', flag: 'CY'.toLowerCase()},
  {text: 'Czech Republic', value: 'CZ', key: 'CZ', flag: 'CZ'.toLowerCase()},
  {text: 'Denmark', value: 'DK', key: 'DK', flag: 'DK'.toLowerCase()},
  {text: 'Djibouti', value: 'DJ', key: 'DJ', flag: 'DJ'.toLowerCase()},
  {text: 'Dominica', value: 'DM', key: 'DM', flag: 'DM'.toLowerCase()},
  {text: 'Dominican Republic', value: 'DO', key: 'DO', flag: 'DO'.toLowerCase()},
  {text: 'Ecuador', value: 'EC', key: 'EC', flag: 'EC'.toLowerCase()},
  {text: 'Egypt', value: 'EG', key: 'EG', flag: 'EG'.toLowerCase()},
  {text: 'El Salvador', value: 'SV', key: 'SV', flag: 'SV'.toLowerCase()},
  {text: 'Equatorial Guinea', value: 'GQ', key: 'GQ', flag: 'GQ'.toLowerCase()},
  {text: 'Eritrea', value: 'ER', key: 'ER', flag: 'ER'.toLowerCase()},
  {text: 'Estonia', value: 'EE', key: 'EE', flag: 'EE'.toLowerCase()},
  {text: 'Ethiopia', value: 'ET', key: 'ET', flag: 'ET'.toLowerCase()},
  {text: 'Falkland Islands (Malvinas)', value: 'FK', key: 'FK', flag: 'FK'.toLowerCase()},
  {text: 'Faroe Islands', value: 'FO', key: 'FO', flag: 'FO'.toLowerCase()},
  {text: 'Fiji', value: 'FJ', key: 'FJ', flag: 'FJ'.toLowerCase()},
  {text: 'Finland', value: 'FI', key: 'FI', flag: 'FI'.toLowerCase()},
  {text: 'France', value: 'FR', key: 'FR', flag: 'FR'.toLowerCase()},
  {text: 'French Guiana', value: 'GF', key: 'GF', flag: 'GF'.toLowerCase()},
  {text: 'French Polynesia', value: 'PF', key: 'PF', flag: 'PF'.toLowerCase()},
  {text: 'French Southern Territories', value: 'TF', key: 'TF', flag: 'TF'.toLowerCase()},
  {text: 'Gabon', value: 'GA', key: 'GA', flag: 'GA'.toLowerCase()},
  {text: 'Gambia', value: 'GM', key: 'GM', flag: 'GM'.toLowerCase()},
  {text: 'Georgia', value: 'GE', key: 'GE', flag: 'GE'.toLowerCase()},
  {text: 'Germany', value: 'DE', key: 'DE', flag: 'DE'.toLowerCase()},
  {text: 'Ghana', value: 'GH', key: 'GH', flag: 'GH'.toLowerCase()},
  {text: 'Gibraltar', value: 'GI', key: 'GI', flag: 'GI'.toLowerCase()},
  {text: 'Greece', value: 'GR', key: 'GR', flag: 'GR'.toLowerCase()},
  {text: 'Greenland', value: 'GL', key: 'GL', flag: 'GL'.toLowerCase()},
  {text: 'Grenada', value: 'GD', key: 'GD', flag: 'GD'.toLowerCase()},
  {text: 'Guadeloupe', value: 'GP', key: 'GP', flag: 'GP'.toLowerCase()},
  {text: 'Guam', value: 'GU', key: 'GU', flag: 'GU'.toLowerCase()},
  {text: 'Guatemala', value: 'GT', key: 'GT', flag: 'GT'.toLowerCase()},
  {text: 'Guinea', value: 'GN', key: 'GN', flag: 'GN'.toLowerCase()},
  {text: 'Guinea-Bissau', value: 'GW', key: 'GW', flag: 'GW'.toLowerCase()},
  {text: 'Guyana', value: 'GY', key: 'GY', flag: 'GY'.toLowerCase()},
  {text: 'Haiti', value: 'HT', key: 'HT', flag: 'HT'.toLowerCase()},
  {text: 'Heard Island and Mcdonald Islands', value: 'HM', key: 'HM', flag: 'HM'.toLowerCase()},
  {text: 'Holy See (Vatican City State)', value: 'VA', key: 'VA', flag: 'VA'.toLowerCase()},
  {text: 'Honduras', value: 'HN', key: 'HN', flag: 'HN'.toLowerCase()},
  {text: 'Hong Kong', value: 'HK', key: 'HK', flag: 'HK'.toLowerCase()},
  {text: 'Hungary', value: 'HU', key: 'HU', flag: 'HU'.toLowerCase()},
  {text: 'Iceland', value: 'IS', key: 'IS', flag: 'IS'.toLowerCase()},
  {text: 'India', value: 'IN', key: 'IN', flag: 'IN'.toLowerCase()},
  {text: 'Indonesia', value: 'ID', key: 'ID', flag: 'ID'.toLowerCase()},
  {text: 'Iran, Islamic Republic Of', value: 'IR', key: 'IR', flag: 'IR'.toLowerCase()},
  {text: 'Iraq', value: 'IQ', key: 'IQ', flag: 'IQ'.toLowerCase()},
  {text: 'Ireland', value: 'IE', key: 'IE', flag: 'IE'.toLowerCase()},
  {text: 'Israel', value: 'IL', key: 'IL', flag: 'IL'.toLowerCase()},
  {text: 'Italy', value: 'IT', key: 'IT', flag: 'IT'.toLowerCase()},
  {text: 'Jamaica', value: 'JM', key: 'JM', flag: 'JM'.toLowerCase()},
  {text: 'Japan', value: 'JP', key: 'JP', flag: 'JP'.toLowerCase()},
  {text: 'Jordan', value: 'JO', key: 'JO', flag: 'JO'.toLowerCase()},
  {text: 'Kazakhstan', value: 'KZ', key: 'KZ', flag: 'KZ'.toLowerCase()},
  {text: 'Kenya', value: 'KE', key: 'KE', flag: 'KE'.toLowerCase()},
  {text: 'Kiribati', value: 'KI', key: 'KI', flag: 'KI'.toLowerCase()},
  {text: 'Korea, Democratic People\'S Republic of', value: 'KP', key: 'KP', flag: 'KP'.toLowerCase()},
  {text: 'Korea, Republic of', value: 'KR', key: 'KR', flag: 'KR'.toLowerCase()},
  {text: 'Kuwait', value: 'KW', key: 'KW', flag: 'KW'.toLowerCase()},
  {text: 'Kyrgyzstan', value: 'KG', key: 'KG', flag: 'KG'.toLowerCase()},
  {text: 'Lao People\'S Democratic Republic', value: 'LA', key: 'LA', flag: 'LA'.toLowerCase()},
  {text: 'Latvia', value: 'LV', key: 'LV', flag: 'LV'.toLowerCase()},
  {text: 'Lebanon', value: 'LB', key: 'LB', flag: 'LB'.toLowerCase()},
  {text: 'Lesotho', value: 'LS', key: 'LS', flag: 'LS'.toLowerCase()},
  {text: 'Liberia', value: 'LR', key: 'LR', flag: 'LR'.toLowerCase()},
  {text: 'Libyan Arab Jamahiriya', value: 'LY', key: 'LY', flag: 'LY'.toLowerCase()},
  {text: 'Liechtenstein', value: 'LI', key: 'LI', flag: 'LI'.toLowerCase()},
  {text: 'Lithuania', value: 'LT', key: 'LT', flag: 'LT'.toLowerCase()},
  {text: 'Luxembourg', value: 'LU', key: 'LU', flag: 'LU'.toLowerCase()},
  {text: 'Macao', value: 'MO', key: 'MO', flag: 'MO'.toLowerCase()},
  {text: 'Macedonia, The Former Yugoslav Republic of', value: 'MK', key: 'MK', flag: 'MK'.toLowerCase()},
  {text: 'Madagascar', value: 'MG', key: 'MG', flag: 'MG'.toLowerCase()},
  {text: 'Malawi', value: 'MW', key: 'MW', flag: 'MW'.toLowerCase()},
  {text: 'Malaysia', value: 'MY', key: 'MY', flag: 'MY'.toLowerCase()},
  {text: 'Maldives', value: 'MV', key: 'MV', flag: 'MV'.toLowerCase()},
  {text: 'Mali', value: 'ML', key: 'ML', flag: 'ML'.toLowerCase()},
  {text: 'Malta', value: 'MT', key: 'MT', flag: 'MT'.toLowerCase()},
  {text: 'Marshall Islands', value: 'MH', key: 'MH', flag: 'MH'.toLowerCase()},
  {text: 'Martinique', value: 'MQ', key: 'MQ', flag: 'MQ'.toLowerCase()},
  {text: 'Mauritania', value: 'MR', key: 'MR', flag: 'MR'.toLowerCase()},
  {text: 'Mauritius', value: 'MU', key: 'MU', flag: 'MU'.toLowerCase()},
  {text: 'Mayotte', value: 'YT', key: 'YT', flag: 'YT'.toLowerCase()},
  {text: 'Mexico', value: 'MX', key: 'MX', flag: 'MX'.toLowerCase()},
  {text: 'Micronesia, Federated States of', value: 'FM', key: 'FM', flag: 'FM'.toLowerCase()},
  {text: 'Moldova, Republic of', value: 'MD', key: 'MD', flag: 'MD'.toLowerCase()},
  {text: 'Monaco', value: 'MC', key: 'MC', flag: 'MC'.toLowerCase()},
  {text: 'Mongolia', value: 'MN', key: 'MN', flag: 'MN'.toLowerCase()},
  {text: 'Montserrat', value: 'MS', key: 'MS', flag: 'MS'.toLowerCase()},
  {text: 'Morocco', value: 'MA', key: 'MA', flag: 'MA'.toLowerCase()},
  {text: 'Mozambique', value: 'MZ', key: 'MZ', flag: 'MZ'.toLowerCase()},
  {text: 'Myanmar', value: 'MM', key: 'MM', flag: 'MM'.toLowerCase()},
  {text: 'Namibia', value: 'NA', key: 'NA', flag: 'NA'.toLowerCase()},
  {text: 'Nauru', value: 'NR', key: 'NR', flag: 'NR'.toLowerCase()},
  {text: 'Nepal', value: 'NP', key: 'NP', flag: 'NP'.toLowerCase()},
  {text: 'Netherlands', value: 'NL', key: 'NL', flag: 'NL'.toLowerCase()},
  {text: 'Netherlands Antilles', value: 'AN', key: 'AN', flag: 'AN'.toLowerCase()},
  {text: 'New Caledonia', value: 'NC', key: 'NC', flag: 'NC'.toLowerCase()},
  {text: 'New Zealand', value: 'NZ', key: 'NZ', flag: 'NZ'.toLowerCase()},
  {text: 'Nicaragua', value: 'NI', key: 'NI', flag: 'NI'.toLowerCase()},
  {text: 'Niger', value: 'NE', key: 'NE', flag: 'NE'.toLowerCase()},
  {text: 'Nigeria', value: 'NG', key: 'NG', flag: 'NG'.toLowerCase()},
  {text: 'Niue', value: 'NU', key: 'NU', flag: 'NU'.toLowerCase()},
  {text: 'Norfolk Island', value: 'NF', key: 'NF', flag: 'NF'.toLowerCase()},
  {text: 'Northern Mariana Islands', value: 'MP', key: 'MP', flag: 'MP'.toLowerCase()},
  {text: 'Norway', value: 'NO', key: 'NO', flag: 'NO'.toLowerCase()},
  {text: 'Oman', value: 'OM', key: 'OM', flag: 'OM'.toLowerCase()},
  {text: 'Pakistan', value: 'PK', key: 'PK', flag: 'PK'.toLowerCase()},
  {text: 'Palau', value: 'PW', key: 'PW', flag: 'PW'.toLowerCase()},
  {text: 'Palestinian Territory, Occupied', value: 'PS', key: 'PS', flag: 'PS'.toLowerCase()},
  {text: 'Panama', value: 'PA', key: 'PA', flag: 'PA'.toLowerCase()},
  {text: 'Papua New Guinea', value: 'PG', key: 'PG', flag: 'PG'.toLowerCase()},
  {text: 'Paraguay', value: 'PY', key: 'PY', flag: 'PY'.toLowerCase()},
  {text: 'Peru', value: 'PE', key: 'PE', flag: 'PE'.toLowerCase()},
  {text: 'Philippines', value: 'PH', key: 'PH', flag: 'PH'.toLowerCase()},
  {text: 'Pitcairn', value: 'PN', key: 'PN', flag: 'PN'.toLowerCase()},
  {text: 'Poland', value: 'PL', key: 'PL', flag: 'PL'.toLowerCase()},
  {text: 'Portugal', value: 'PT', key: 'PT', flag: 'PT'.toLowerCase()},
  {text: 'Puerto Rico', value: 'PR', key: 'PR', flag: 'PR'.toLowerCase()},
  {text: 'Qatar', value: 'QA', key: 'QA', flag: 'QA'.toLowerCase()},
  {text: 'Reunion', value: 'RE', key: 'RE', flag: 'RE'.toLowerCase()},
  {text: 'Romania', value: 'RO', key: 'RO', flag: 'RO'.toLowerCase()},
  {text: 'Russian Federation', value: 'RU', key: 'RU', flag: 'RU'.toLowerCase()},
  {text: 'RWANDA', value: 'RW', key: 'RW', flag: 'RW'.toLowerCase()},
  {text: 'Saint Helena', value: 'SH', key: 'SH', flag: 'SH'.toLowerCase()},
  {text: 'Saint Kitts and Nevis', value: 'KN', key: 'KN', flag: 'KN'.toLowerCase()},
  {text: 'Saint Lucia', value: 'LC', key: 'LC', flag: 'LC'.toLowerCase()},
  {text: 'Saint Pierre and Miquelon', value: 'PM', key: 'PM', flag: 'PM'.toLowerCase()},
  {text: 'Saint Vincent and the Grenadines', value: 'VC', key: 'VC', flag: 'VC'.toLowerCase()},
  {text: 'Samoa', value: 'WS', key: 'WS', flag: 'WS'.toLowerCase()},
  {text: 'San Marino', value: 'SM', key: 'SM', flag: 'SM'.toLowerCase()},
  {text: 'Sao Tome and Principe', value: 'ST', key: 'ST', flag: 'ST'.toLowerCase()},
  {text: 'Saudi Arabia', value: 'SA', key: 'SA', flag: 'SA'.toLowerCase()},
  {text: 'Senegal', value: 'SN', key: 'SN', flag: 'SN'.toLowerCase()},
  {text: 'Serbia and Montenegro', value: 'CS', key: 'CS', flag: 'CS'.toLowerCase()},
  {text: 'Seychelles', value: 'SC', key: 'SC', flag: 'SC'.toLowerCase()},
  {text: 'Sierra Leone', value: 'SL', key: 'SL', flag: 'SL'.toLowerCase()},
  {text: 'Singapore', value: 'SG', key: 'SG', flag: 'SG'.toLowerCase()},
  {text: 'Slovakia', value: 'SK', key: 'SK', flag: 'SK'.toLowerCase()},
  {text: 'Slovenia', value: 'SI', key: 'SI', flag: 'SI'.toLowerCase()},
  {text: 'Solomon Islands', value: 'SB', key: 'SB', flag: 'SB'.toLowerCase()},
  {text: 'Somalia', value: 'SO', key: 'SO', flag: 'SO'.toLowerCase()},
  {text: 'South Africa', value: 'ZA', key: 'ZA', flag: 'ZA'.toLowerCase()},
  {text: 'South Georgia and the South Sandwich Islands', value: 'GS', key: 'GS', flag: 'GS'.toLowerCase()},
  {text: 'Spain', value: 'ES', key: 'ES', flag: 'ES'.toLowerCase()},
  {text: 'Sri Lanka', value: 'LK', key: 'LK', flag: 'LK'.toLowerCase()},
  {text: 'Sudan', value: 'SD', key: 'SD', flag: 'SD'.toLowerCase()},
  {text: 'Suritext', value: 'SR', key: 'SR', flag: 'SR'.toLowerCase()},
  {text: 'Svalbard and Jan Mayen', value: 'SJ', key: 'SJ', flag: 'SJ'.toLowerCase()},
  {text: 'Swaziland', value: 'SZ', key: 'SZ', flag: 'SZ'.toLowerCase()},
  {text: 'Sweden', value: 'SE', key: 'SE', flag: 'SE'.toLowerCase()},
  {text: 'Switzerland', value: 'CH', key: 'CH', flag: 'CH'.toLowerCase()},
  {text: 'Syrian Arab Republic', value: 'SY', key: 'SY', flag: 'SY'.toLowerCase()},
  {text: 'Taiwan, Province of China', value: 'TW', key: 'TW', flag: 'TW'.toLowerCase()},
  {text: 'Tajikistan', value: 'TJ', key: 'TJ', flag: 'TJ'.toLowerCase()},
  {text: 'Tanzania, United Republic of', value: 'TZ', key: 'TZ', flag: 'TZ'.toLowerCase()},
  {text: 'Thailand', value: 'TH', key: 'TH', flag: 'TH'.toLowerCase()},
  {text: 'Timor-Leste', value: 'TL', key: 'TL', flag: 'TL'.toLowerCase()},
  {text: 'Togo', value: 'TG', key: 'TG', flag: 'TG'.toLowerCase()},
  {text: 'Tokelau', value: 'TK', key: 'TK', flag: 'TK'.toLowerCase()},
  {text: 'Tonga', value: 'TO', key: 'TO', flag: 'TO'.toLowerCase()},
  {text: 'Trinidad and Tobago', value: 'TT', key: 'TT', flag: 'TT'.toLowerCase()},
  {text: 'Tunisia', value: 'TN', key: 'TN', flag: 'TN'.toLowerCase()},
  {text: 'Turkey', value: 'TR', key: 'TR', flag: 'TR'.toLowerCase()},
  {text: 'Turkmenistan', value: 'TM', key: 'TM', flag: 'TM'.toLowerCase()},
  {text: 'Turks and Caicos Islands', value: 'TC', key: 'TC', flag: 'TC'.toLowerCase()},
  {text: 'Tuvalu', value: 'TV', key: 'TV', flag: 'TV'.toLowerCase()},
  {text: 'Uganda', value: 'UG', key: 'UG', flag: 'UG'.toLowerCase()},
  {text: 'Ukraine', value: 'UA', key: 'UA', flag: 'UA'.toLowerCase()},
  {text: 'United Arab Emirates', value: 'AE', key: 'AE', flag: 'AE'.toLowerCase()},
  {text: 'United Kingdom', value: 'GB', key: 'GB', flag: 'GB'.toLowerCase()},
  {text: 'United States', value: 'US', key: 'US', flag: 'US'.toLowerCase()},
  {text: 'United States Minor Outlying Islands', value: 'UM', key: 'UM', flag: 'UM'.toLowerCase()},
  {text: 'Uruguay', value: 'UY', key: 'UY', flag: 'UY'.toLowerCase()},
  {text: 'Uzbekistan', value: 'UZ', key: 'UZ', flag: 'UZ'.toLowerCase()},
  {text: 'Vanuatu', value: 'VU', key: 'VU', flag: 'VU'.toLowerCase()},
  {text: 'Venezuela', value: 'VE', key: 'VE', flag: 'VE'.toLowerCase()},
  {text: 'Viet Nam', value: 'VN', key: 'VN', flag: 'VN'.toLowerCase()},
  {text: 'Virgin Islands, British', value: 'VG', key: 'VG', flag: 'VG'.toLowerCase()},
  {text: 'Virgin Islands, U.S.', value: 'VI', key: 'VI', flag: 'VI'.toLowerCase()},
  {text: 'Wallis and Futuna', value: 'WF', key: 'WF', flag: 'WF'.toLowerCase()},
  {text: 'Western Sahara', value: 'EH', key: 'EH', flag: 'EH'.toLowerCase()},
  {text: 'Yemen', value: 'YE', key: 'YE', flag: 'YE'.toLowerCase()},
  {text: 'Zambia', value: 'ZM', key: 'ZM', flag: 'ZM'.toLowerCase()},
  {text: 'Zimbabwe', value: 'ZW', key: 'ZW', flag: 'ZW'.toLowerCase()}
];

export const LANG = [
  {value: "ab", key:"Abkhaz", text :"Abkhaz & аҧсуа"},
  {value: "aa", key:"Afar", text :"Afar & Afaraf"},
  {value: "af", key:"Afrikaans", text :"Afrikaans & Afrikaans"},
  {value: "ak", key:"Akan", text :"Akan & Akan"},
  {value: "sq", key:"Albanian", text :"Albanian & Shqip"},
  {value: "am", key:"Amharic", text :"Amharic & አማርኛ"},
  {value: "ar", key:"Arabic", text :"Arabic & العربية"},
  {value: "an", key:"Aragonese", text :"Aragonese & Aragonés"},
  {value: "hy", key:"Armenian", text :"Armenian & Հայերեն"},
  {value: "as", key:"Assamese", text :"Assamese & অসমীয়া"},
  {value: "av", key:"Avaric", text :"Avaric & авар мацӀ"},
  {value: "ae", key:"Avestan", text :"Avestan & avesta"},
  {value: "ay", key:"Aymara", text :"Aymara & aymar aru"},
  {value: "az", key:"Azerbaijani", text :"Azerbaijani & azərbaycan dili"},
  {value: "bm", key:"Bambara", text :"Bambara & bamanankan"},
  {value: "ba", key:"Bashkir", text :"Bashkir & башҡорт теле"},
  {value: "eu", key:"Basque", text :"Basque & euskara"},
  {value: "be", key:"Belarusian", text :"Belarusian & Беларуская"},
  {value: "bn", key:"Bengali", text :"Bengali & বাংলা"},
  {value: "bh", key:"Bihari", text :"Bihari & भोजपुरी"},
  {value: "bi", key:"Bislama", text :"Bislama & Bislama"},
  {value: "bs", key:"Bosnian", text :"Bosnian & bosanski jezik"},
  {value: "br", key:"Breton", text :"Breton & brezhoneg"},
  {value: "bg", key:"Bulgarian", text :"Bulgarian & български език"},
  {value: "my", key:"Burmese", text :"Burmese & ဗမာစာ"},
  {value: "ca", key:"Catalan; Valencian", text :"Catalan & Català"},
  {value: "ch", key:"Chamorro", text :"Chamorro & Chamoru"},
  {value: "ce", key:"Chechen", text :"Chechen & нохчийн мотт"},
  {value: "ny", key:"Chichewa; Chewa; Nyanja", text :"Chichewa & chiCheŵa"},
  {value: "zh", key:"Chinese", text :"Chinese & 中文 (Zhōngwén)"},
  {value: "cv", key:"Chuvash", text :"Chuvash & чӑваш чӗлхи"},
  {value: "kw", key:"Cornish", text :"Cornish & Kernewek"},
  {value: "co", key:"Corsican", text :"Corsican & corsu, lingua corsa"},
  {value: "cr", key:"Cree", text :"Cree & ᓀᐦᐃᔭᐍᐏᐣ"},
  {value: "hr", key:"Croatian", text :"Croatian & hrvatski"},
  {value: "cs", key:"Czech", text :"Czech & česky, čeština"},
  {value: "da", key:"Danish", text :"Danish & dansk"},
  {value: "dv", key:"Divehi; Dhivehi; Maldivian;", text :"Divehi & ދިވެހި"},
  {value: "nl", key:"Dutch", text :"Dutch & Nederlands"},
  {value: "en", key:"English", text :"English & English"},
  {value: "eo", key:"Esperanto", text :"Esperanto & Esperanto"},
  {value: "et", key:"Estonian", text :"Estonian & eesti"},
  {value: "ee", key:"Ewe", text :"Ewe & Eʋegbe"},
  {value: "fo", key:"Faroese", text :"Faroese & føroyskt"},
  {value: "fj", key:"Fijian", text :"Fijian & vosa Vakaviti"},
  {value: "fi", key:"Finnish", text :"Finnish & suomi"},
  {value: "fr", key:"French", text :"French & français"},
  {value: "ff", key:"Fula; Fulah; Pulaar; Pular", text :"Fula & Fulfulde"},
  {value: "gl", key:"Galician", text :"Galician & Galego"},
  {value: "ka", key:"Georgian", text :"Georgian & ქართული"},
  {value: "de", key:"German", text :"German & Deutsch"},
  {value: "el", key:"Greek, Modern", text :"Greek & Ελληνικά"},
  {value: "gn", key:"Guaraní", text :"Guaraní & Avañeẽ"},
  {value: "gu", key:"Gujarati", text :"Gujarati & ગુજરાતી"},
  {value: "ht", key:"Haitian; Haitian Creole", text :"Haitian & Kreyòl ayisyen"},
  {value: "ha", key:"Hausa", text :"Hausa & Hausa, هَوُسَ"},
  {value: "he", key:"Hebrew (modern)", text :"Hebrew & עברית"},
  {value: "hz", key:"Herero", text :"Herero & Otjiherero"},
  {value: "hi", key:"Hindi", text :"Hindi & हिन्दी, हिंदी"},
  {value: "ho", key:"Hiri Motu", text :"Hiri & Hiri Motu"},
  {value: "hu", key:"Hungarian", text :"Hungarian & Magyar"},
  {value: "ia", key:"Interlingua", text :"Interlingua & Interlingua"},
  {value: "id", key:"Indonesian", text :"Indonesian & Bahasa Indonesia"},
  {value: "ie", key:"Interlingue", text :"Interlingue & Interlingue"},
  {value: "ga", key:"Irish", text :"Irish & Gaeilge"},
  {value: "ig", key:"Igbo", text :"Igbo & Asụsụ Igbo"},
  {value: "ik", key:"Inupiaq", text :"Inupiaq & Iñupiaq"},
  {value: "io", key:"Ido", text :"Ido & Ido"},
  {value: "is", key:"Icelandic", text :"Icelandic & Íslenska"},
  {value: "it", key:"Italian", text :"Italian & Italiano"},
  {value: "iu", key:"Inuktitut", text :"Inuktitut & ᐃᓄᒃᑎᑐᑦ"},
  {value: "ja", key:"Japanese", text :"Japanese & 日本語"},
  {value: "jv", key:"Javanese", text :"Javanese & basa Jawa"},
  {value: "kl", key:"Kalaallisut, Greenlandic", text :"Kalaallisut & kalaallisut"},
  {value: "kn", key:"Kannada", text :"Kannada & ಕನ್ನಡ"},
  {value: "kr", key:"Kanuri", text :"Kanuri & Kanuri"},
  {value: "ks", key:"Kashmiri", text :"Kashmiri & कश्मीरी"},
  {value: "kk", key:"Kazakh", text :"Kazakh & Қазақ тілі"},
  {value: "km", key:"Khmer", text :"Khmer & ភាសាខ្មែរ"},
  {value: "ki", key:"Kikuyu, Gikuyu", text :"Kikuyu & Gĩkũyũ"},
  {value: "rw", key:"Kinyarwanda", text :"Kinyarwanda & Ikinyarwanda"},
  {value: "ky", key:"Kirghiz, Kyrgyz", text :"Kirghiz & кыргыз тили"},
  {value: "kv", key:"Komi", text :"Komi & коми кыв"},
  {value: "kg", key:"Kongo", text :"Kongo & KiKongo"},
  {value: "ko", key:"Korean", text :"Korean & 한국어"},
  {value: "ku", key:"Kurdish", text :"Kurdish & Kurdî"},
  {value: "kj", key:"Kwanyama, Kuanyama", text :"Kwanyama & Kuanyama"},
  {value: "la", key:"Latin", text :"Latin & latine"},
  {value: "lb", key:"Luxembourgish, Letzeburgesch", text :"Luxembourgish & Lëtzebuergesch"},
  {value: "lg", key:"Luganda", text :"Luganda & Luganda"},
  {value: "li", key:"Limburgish, Limburgan, Limburger", text :"Limburgish & Limburgs"},
  {value: "ln", key:"Lingala", text :"Lingala & Lingála"},
  {value: "lo", key:"Lao", text :"Lao & ພາສາລາວ"},
  {value: "lt", key:"Lithuanian", text :"Lithuanian & lietuvių kalba"},
  {value: "lu", key:"Luba-Katanga", text :"Luba & "},
  {value: "lv", key:"Latvian", text :"Latvian & latviešu valoda"},
  {value: "gv", key:"Manx", text :"Manx & Gaelg"},
  {value: "mk", key:"Macedonian", text :"Macedonian & македонски јазик"},
  {value: "mg", key:"Malagasy", text :"Malagasy & Malagasy fiteny"},
  {value: "ms", key:"Malay", text :"Malay & bahasa Melayu‎"},
  {value: "ml", key:"Malayalam", text :"Malayalam & മലയാളം"},
  {value: "mt", key:"Maltese", text :"Maltese & Malti"},
  {value: "mi", key:"Māori", text :"Māori & te reo Māori"},
  {value: "mr", key:"Marathi (Marāṭhī)", text :"Marathi & मराठी"},
  {value: "mh", key:"Marshallese", text :"Marshallese & Kajin M̧ajeļ"},
  {value: "mn", key:"Mongolian", text :"Mongolian & монгол"},
  {value: "na", key:"Nauru", text :"Nauru & Ekakairũ Naoero"},
  {value: "nv", key:"Navajo, Navaho", text :"Navajo & Diné bizaad"},
  {value: "nb", key:"Norwegian Bokmål", text :"Norwegian & Norsk bokmål"},
  {value: "nd", key:"North Ndebele", text :"North & isiNdebele"},
  {value: "ne", key:"Nepali", text :"Nepali & नेपाली"},
  {value: "ng", key:"Ndonga", text :"Ndonga & Owambo"},
  {value: "nn", key:"Norwegian Nynorsk", text :"Norwegian & Norsk nynorsk"},
  {value: "no", key:"Norwegian", text :"Norwegian & Norsk"},
  {value: "ii", key:"Nuosu", text :"Nuosu & ꆈꌠ꒿ Nuosuhxop"},
  {value: "nr", key:"South Ndebele", text :"South & isiNdebele"},
  {value: "oc", key:"Occitan", text :"Occitan & Occitan"},
  {value: "oj", key:"Ojibwe, Ojibwa", text :"Ojibwe & ᐊᓂᔑᓈᐯᒧᐎᓐ"},
  {value: "cu", key:"Old Church Slavonic", text :"Old & ѩзыкъ словѣньскъ"},
  {value: "om", key:"Oromo", text :"Oromo & Afaan Oromoo"},
  {value: "or", key:"Oriya", text :"Oriya & ଓଡ଼ିଆ"},
  {value: "os", key:"Ossetian, Ossetic", text :"Ossetian & ирон æвзаг"},
  {value: "pa", key:"Panjabi, Punjabi", text :"Panjabi & ਪੰਜਾਬੀ"},
  {value: "pi", key:"Pāli", text :"Pāli & पाऴि"},
  {value: "fa", key:"Persian", text :"Persian & فارسی"},
  {value: "pl", key:"Polish", text :"Polish & polski"},
  {value: "ps", key:"Pashto, Pushto", text :"Pashto & پښتو"},
  {value: "pt", key:"Portuguese", text :"Portuguese & Português"},
  {value: "qu", key:"Quechua", text :"Quechua & Runa Simi"},
  {value: "rm", key:"Romansh", text :"Romansh & rumantsch grischun"},
  {value: "rn", key:"Kirundi", text :"Kirundi & kiRundi"},
  {value: "ro", key:"Romanian, Moldavian, Moldovan", text :"Romanian & română"},
  {value: "ru", key:"Russian", text :"Russian & русский язык"},
  {value: "sa", key:"Sanskrit (Saṁskṛta)", text :"Sanskrit & संस्कृतम्"},
  {value: "sc", key:"Sardinian", text :"Sardinian & sardu"},
  {value: "sd", key:"Sindhi", text :"Sindhi & सिन्धी"},
  {value: "se", key:"Northern Sami", text :"Northern & Davvisámegiella"},
  {value: "sm", key:"Samoan", text :"Samoan & gagana faa Samoa"},
  {value: "sg", key:"Sango", text :"Sango & yângâ tî sängö"},
  {value: "sr", key:"Serbian", text :"Serbian & српски језик"},
  {value: "gd", key:"Scottish Gaelic; Gaelic", text :"Scottish & Gàidhlig"},
  {value: "sn", key:"Shona", text :"Shona & chiShona"},
  {value: "si", key:"Sinhala, Sinhalese", text :"Sinhala & සිංහල"},
  {value: "sk", key:"Slovak", text :"Slovak & slovenčina"},
  {value: "sl", key:"Slovene", text :"Slovene & slovenščina"},
  {value: "so", key:"Somali", text :"Somali & Soomaaliga"},
  {value: "st", key:"Southern Sotho", text :"Southern & Sesotho"},
  {value: "es", key:"Spanish; Castilian", text :"Spanish & español"},
  {value: "su", key:"Sundanese", text :"Sundanese & Basa Sunda"},
  {value: "sw", key:"Swahili", text :"Swahili & Kiswahili"},
  {value: "ss", key:"Swati", text :"Swati & SiSwati"},
  {value: "sv", key:"Swedish", text :"Swedish & svenska"},
  {value: "ta", key:"Tamil", text :"Tamil & தமிழ்"},
  {value: "te", key:"Telugu", text :"Telugu & తెలుగు"},
  {value: "tg", key:"Tajik", text :"Tajik & тоҷикӣ"},
  {value: "th", key:"Thai", text :"Thai & ไทย"},
  {value: "ti", key:"Tigrinya", text :"Tigrinya & ትግርኛ"},
  {value: "bo", key:"Tibetan Standard, Tibetan, Central", text :"Tibetan & བོད་ཡིག"},
  {value: "tk", key:"Turkmen", text :"Turkmen & Türkmen"},
  {value: "tl", key:"Tagalog", text :"Tagalog & Wikang Tagalog"},
  {value: "tn", key:"Tswana", text :"Tswana & Setswana"},
  {value: "to", key:"Tonga (Tonga Islands)", text :"Tonga & faka Tonga"},
  {value: "tr", key:"Turkish", text :"Turkish & Türkçe"},
  {value: "ts", key:"Tsonga", text :"Tsonga & Xitsonga"},
  {value: "tt", key:"Tatar", text :"Tatar & татарча"},
  {value: "tw", key:"Twi", text :"Twi & Twi"},
  {value: "ty", key:"Tahitian", text :"Tahitian & Reo Tahiti"},
  {value: "ug", key:"Uighur, Uyghur", text :"Uighur & Uyƣurqə"},
  {value: "uk", key:"Ukrainian", text :"Ukrainian & українська"},
  {value: "ur", key:"Urdu", text :"Urdu & اردو"},
  {value: "uz", key:"Uzbek", text :"Uzbek & zbek"},
  {value: "ve", key:"Venda", text :"Venda & Tshivenḓa"},
  {value: "vi", key:"Vietnamese", text :"Vietnamese & Tiếng Việt"},
  {value: "vo", key:"Volapük", text :"Volapük & Volapük"},
  {value: "wa", key:"Walloon", text :"Walloon & Walon"},
  {value: "cy", key:"Welsh", text :"Welsh & Cymraeg"},
  {value: "wo", key:"Wolof", text :"Wolof & Wollof"},
  {value: "fy", key:"Western Frisian", text :"Western & Frysk"},
  {value: "xh", key:"Xhosa", text :"Xhosa & isiXhosa"},
  {value: "yi", key:"Yiddish", text :"Yiddish & ייִדיש"},
  {value: "yo", key:"Yoruba", text :"Yoruba & Yorùbá"},
  {value: "za", key:"Zhuang, Chuang", text :"Zhuang & Saɯ cueŋƅ"}
]

export const MENU = [
  {text: 'food & drink', key: 'food', value: 'food', icon: 'food'},
  {text: 'map & transport', key: 'map', value: 'map', icon: 'map marker alternate'},
  {text: 'travel info', key: 'travel', value: 'travel', icon: 'info circle'},
]